---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pl-stan
spec:
  replicas: 3
  volumeClaimTemplates:
  - metadata:
      name: stan-sts-vol
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pixie-nfs
      volumeMode: "Filesystem"
      resources:
        requests:
          storage: 1Gi
