---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: pixie-nfs
  resources:
    requests:
      storage: 100M
