---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    cloud.google.com/load-balancer-type: external
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 5432
  selector:
    name: postgres
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres
#spec:
#  ports:
#  - port: 5432
#  selector:
#    name: postgres
