---
apiVersion: v1
kind: Service
metadata:
  name: cloud-proxy-service
  annotations:
    cloud.google.com/load-balancer-type: external
spec:
  type: NodePort
  ports:
  - port: 443
    protocol: TCP
    targetPort: 56000
    nodePort: 443
    name: tcp-https
  - port: 4444
    protocol: TCP
    targetPort: 56004
    nodePort: 4444
    name: tcp-grcp-web
  - port: 5555
    protocol: TCP
    targetPort: 56000
    nodePort: 5555
    name: tcp-http2
  selector:
    name: cloud-proxy-server
