---
apiVersion: v1
kind: Service
metadata:
  name: vzconn-service
  annotations:
    cloud.google.com/load-balancer-type: external
    cloud.google.com/app-protocols: '{"tcp-http2":"HTTP2"}'
spec:
  type: NodePort
  ports:
  - port: 51600
    protocol: TCP
    targetPort: 51600
    nodePort: 51600
    name: tcp-http2
  selector:
    name: vzconn-server
